import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./nav/NavBar";
import ToasterProvider from "./providers/ToasterProvider";
import SignalRProvider from "./providers/SignalRProvider";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Carsties",
  description: "Generated by create next app",
};

//export const dynamic = 'force-dynamic';

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const user = await getCurrentUser();

  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <ToasterProvider />
          <NavBar />
          <main className="container mx-auto px-5 pt-10">
            <SignalRProvider>
              {children}
            </SignalRProvider>
          </main>
        </SessionProvider>
        
      </body>
    </html>
  );
}
